python:
  - changed-files:
      - any-glob-to-any-file: 'python-zerosmtp.py'
php:
  - changed-files:
      - any-glob-to-any-file:
          - 'php-zerosmtp.php'
          - 'php-symfony-mailer-zerosmtp.php'
          - 'composer.json'
node:
  - changed-files:
      - any-glob-to-any-file:
          - 'node-zerosmtp.mjs'
          - 'ts-zerosmtp.ts'
          - 'package.json'
          - 'tsconfig.json'
bash:
  - changed-files:
      - any-glob-to-any-file:
          - 'bash-curl-zerosmtp.sh'
          - 'bash-swaks-zerosmtp.sh'
          - 'check-connection.sh'
powershell:
  - changed-files:
      - any-glob-to-any-file:
          - 'pwsh-zerosmtp.ps1'
          - 'check-connection.ps1'
          - 'SendEmailTest_mail-tester.com.ps1'
java:
  - changed-files:
      - any-glob-to-any-file:
          - 'java-zerosmtp.java'
          - 'pom.xml'
csharp:
  - changed-files:
      - any-glob-to-any-file:
          - 'cs-zerosmtp.cs'
          - 'cs-zerosmtp.csproj'
go:
  - changed-files:
      - any-glob-to-any-file: 'go-zerosmtp.go'
ruby:
  - changed-files:
      - any-glob-to-any-file: 'ruby-zerosmtp.rb'
lua:
  - changed-files:
      - any-glob-to-any-file: 'lua-zerosmtp.lua'
rust:
  - changed-files:
      - any-glob-to-any-file:
          - 'rust-zerosmtp.rs'
          - 'Cargo.toml'
kotlin:
  - changed-files:
      - any-glob-to-any-file:
          - 'kotlin-zerosmtp.kt'
          - 'build.gradle.kts'
          - 'settings.gradle.kts'
swift:
  - changed-files:
      - any-glob-to-any-file:
          - 'swift-zerosmtp.swift'
          - 'Package.swift'
docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - 'README.md'
          - 'README.pl.md'
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
