#!/usr/bin/env python3
"""Render one page per SMTP error string from data/errors.json.

An error string is the highest-intent query this project can rank for.
Somebody pasting `535 5.7.139 SmtpClientAuthentication is disabled for the
Tenant` into a search box is broken at that moment and is looking for exactly
this - there is no ambiguity about what they want. docs/ERROR-MESSAGES.md
covers six distinct strings on one page, and a page covering six loses each of
them to a page covering one.

Same contract as tools/build-device-table.py: generated, `--check`ed in CI,
orphans removed.

    python tools/build-error-pages.py            # rewrite the pages
    python tools/build-error-pages.py --check    # fail if anything would change
"""

import argparse
import json
import pathlib
import sys

KORZEN = pathlib.Path(__file__).resolve().parent.parent
DANE = KORZEN / "data" / "errors.json"
KATALOG = KORZEN / "docs" / "errors"

# jekyll-seo-tag appends " | ZeroSMTP"; docs/_config.yml documents ~50
# characters for the part before it.
LIMIT_TYTULU = 48

SPOJNIKI = {"is", "was", "for", "the", "a", "an", "to", "of", "by", "not", "be", "been"}

RODZAJE = {"auth-refused", "no-credentials", "wrong-sender", "throttled"}

# Three of the four causes are still reversible before the end of December
# 2026. Saying "you must migrate" to somebody a settings change would have
# fixed is bad advice, and it happens to be the advice that suits us - which
# is exactly why it is written down here once and reused.
PRZYCZYNY = [
    ("An admin disabled SMTP AUTH for the tenant or the mailbox",
     "Yes — until the end of December 2026"),
    ("**Security Defaults**, on by default for recently created tenants",
     "Yes, but it disables more than SMTP and turning it off weakens the tenant"),
    ("A **Conditional Access** policy blocking legacy authentication",
     "Yes, by scoping the policy — but it is usually deliberate, so ask why it exists"),
    ("The **end-of-December-2026 default change**",
     "No"),
]


def tytul(wpis, wyrozniki=None):
    """The code alone is what people paste and what should win the match.

    Words are dropped from the end, which is fine until the word that
    distinguishes two entries happens to be the last one. Measured 2026-08-25:
    "SmtpClientAuthentication is disabled for the Mailbox" and the same string
    ending in "Tenant" both truncated to an identical title. Two pages, one
    title, on the error that defines December 2026 - and a search engine reads
    a duplicate title as a reason to show only one of them.

    Mailbox and Tenant are different problems with different fixes, so the
    distinguishing word has to survive. Pass `wyrozniki` - the set of titles
    already taken - and a colliding entry keeps its last word in brackets.
    """
    pelny = f"{wpis['code']} {wpis['message']}"
    if len(pelny) <= LIMIT_TYTULU and (wyrozniki is None or pelny not in wyrozniki):
        return pelny

    slowa = wpis["message"].split()
    skrocony = None
    while slowa:
        slowa.pop()
        kandydat = f"{wpis['code']} {' '.join(slowa)}"
        if slowa and len(kandydat) <= LIMIT_TYTULU:
            skrocony = kandydat
            break

    if skrocony is None:
        return wpis["code"]
    if wyrozniki is None or skrocony not in wyrozniki:
        return skrocony

    # Kolizja. Ostatnie slowo oryginalu jest tym, co odroznia te dwa wpisy,
    # wiec musi sie zmiescic - reszte skracamy dalej, az zrobi mu miejsce.
    ogon = wpis["message"].split()[-1]
    przyrostek = f" ({ogon})"
    slowa = wpis["message"].split()[:-1]
    while slowa:
        # Slowo funkcyjne tuz przed nawiasem czyta sie jak urwane zdanie -
        # "SmtpClientAuthentication is (Tenant)". Tytul trafia do wynikow
        # wyszukiwania, wiec ma sie konczyc na slowie, ktore cos znaczy.
        while slowa and slowa[-1].lower() in SPOJNIKI:
            slowa.pop()
        if not slowa:
            break
        kandydat = f"{wpis['code']} {' '.join(slowa)}{przyrostek}"
        if len(kandydat) <= LIMIT_TYTULU:
            return kandydat
        slowa.pop()
    return f"{wpis['code']}{przyrostek}"


PRZEGLAD = KORZEN / "docs" / "ERROR-MESSAGES.md"
POCZATEK = "<!-- BEGIN GENERATED INDEX -->"
KONIEC = "<!-- END GENERATED INDEX -->"


def zbuduj_indeks(wpisy):
    """The overview table, one row per entry.

    It used to be written by hand. Eleven pages added on 2026-08-23 never made
    it in, so they sat in the sitemap with nothing linking to them - which is
    the state a search engine treats worst and the one nobody notices, because
    the page is there and loads fine.
    """
    wiersze = []
    for w in sorted(wpisy, key=lambda x: (x["kind"], x["code"])):
        pelny = f'{w["code"]} {w["message"]}'
        pierwsze = w["meaning"].split(". ")[0].rstrip(".") + "."
        wiersze.append(f'| [`{pelny}`](errors/{w["slug"]}.md) | {pierwsze} |')
    return chr(10).join([
        POCZATEK,
        "<!-- Generated by tools/build-error-pages.py from data/errors.json. "
        "Eleven of these pages were orphans - in the sitemap, linked from "
        "nowhere - because this table was maintained by hand and the pages "
        "were not. Edit the JSON. -->",
        "| Error | What it means |",
        "| --- | --- |",
        *wiersze,
        KONIEC,
    ])


def zbuduj(wpis, aktualizacja, tytul_wpisu=None):
    pelny = f"{wpis['code']} {wpis['message']}"

    czesci = [
        "---",
        f"title: {json.dumps(tytul_wpisu or tytul(wpis))}",
        f"description: {json.dumps(f'What {pelny} means, whether it can still be turned back on, and what to do if it cannot.')}",
        "---",
        "",
        "<!-- Generated by tools/build-error-pages.py from data/errors.json.",
        "     Edit the JSON, not this file - CI rejects the two disagreeing. -->",
        "",
        f"# {pelny}",
        "",
        "```",
        pelny,
        "```",
        "",
        wpis["meaning"],
        "",
        # The reader arrived here from a search box with the error already in
        # their clipboard, and the tool that answers it in one line was not
        # mentioned on any of these pages at all. That is a page telling
        # somebody about a problem while withholding the thing that solves it.
        # It goes above every other section for the same reason: they are
        # mid-incident and reading in order.
        "## Check it from the machine that is failing",
        "",
        "```bash",
        f'npx zerosmtp-check --explain "{wpis["code"]} {wpis["message"]}"',
        "```",
        "",
        "No install and nothing sent. It reads the refusal your own client "
        "printed - which is rarely what the server said, because libraries and "
        "device panels rewrite it - and says which of these cases you are in.",
        "",
        "If the send is hanging rather than being refused, the cause is usually "
        "the network and not the credentials. `npx zerosmtp-check` with no "
        "arguments checks ports 25, 587 and 465 from where you are standing.",
        "",
    ]

    if wpis["kind"] == "auth-refused":
        czesci += [
            "**This does not mean your password is wrong.** Nothing about the "
            "credentials changed; the method used to present them was switched "
            "off.",
            "",
            "## Which of the four causes is yours",
            "",
            "Basic auth for SMTP AUTH gets refused in four situations, and the "
            "message the client shows is identical in all of them. Which one you "
            "are in decides whether this is a setting or a migration:",
            "",
            "| Cause | Can you turn it back on? |",
            "| --- | --- |",
            *[f"| {c} | {r} |" for c, r in PRZYCZYNY],
            "",
            "Before the end of December 2026 the first three are the likely "
            "answer, and the fix may be a checkbox rather than a project. After "
            "it, re-enabling stops being an option.",
            "",
            "## Find out which mailboxes are affected",
            "",
            "[`Find-SmtpAuthExposure.ps1`](https://github.com/msgwing/ZeroSMTP/blob/main/Find-SmtpAuthExposure.ps1) "
            "answers this for your own tenant. It is read-only.",
            "",
            "It exists because the one-liner everybody reaches for —",
            "`Get-CASMailbox | Where SmtpClientAuthenticationDisabled -eq $false` "
            "— **misses every mailbox that inherits the tenant setting** rather "
            "than carrying its own, and can therefore report zero on a tenant "
            "that is fully exposed. The script counts all three states "
            "separately.",
            "",
        ]

    if wpis.get("wrappers"):
        czesci += [
            "## The same error in other clothes",
            "",
            "Libraries and device firmware rarely pass the server's message "
            "through unchanged. These are the same refusal:",
            "",
            *[f"- {w}" for w in wpis["wrappers"]],
            "",
            "Kyocera MFPs report it as **send error 1102** / `0x1102`, which "
            "looks like a hardware fault and is not one.",
            "",
        ]

    if wpis["kind"] == "no-credentials":
        czesci += [
            "## Check this before assuming it is the Basic auth shutdown",
            "",
            "This one is worth ruling out cheaply, because the fix is usually "
            "local:",
            "",
            "1. Does the device's SMTP configuration have an authentication "
            "checkbox, and is it off?",
            "2. Was this device previously relaying anonymously through an "
            "internal server that has since been retired or repointed?",
            "3. Is it sending `AUTH` after `MAIL FROM`? Some older firmware "
            "does, and Microsoft 365 will not accept it.",
            "",
            "If authentication is genuinely configured and still refused, you "
            "are looking at "
            "[`535 5.7.139`](535-5-7-139-basic-authentication-is-disabled.md) "
            "instead.",
            "",
        ]

    if wpis["kind"] == "throttled":
        czesci += [
            "## This is not the Basic auth shutdown, and not your credentials",
            "",
            "Authentication succeeded. The message was accepted and then "
            "refused on volume: the tenant has sent more in the last 24 hours "
            "than its limit allows. Changing SMTP settings does nothing here, "
            "and re-enabling SMTP AUTH does nothing either.",
            "",
            "1. Find what is sending. A device stuck in a retry loop can spend "
            "a tenant's daily allowance overnight without anybody noticing.",
            "2. Check whether the send is a burst or a new steady rate. A "
            "burst waits; a steady rate over the limit needs a different route.",
            "3. Limits reset on a rolling 24-hour window, not at midnight, so "
            "sending resumes gradually rather than all at once.",
            "",
            "Worth saying plainly because it is easy to sell against: this is "
            "not a problem a relay fixes by itself. If the volume genuinely "
            "exceeds what the tenant may send, it exceeds what this project "
            "allows too - 200 messages a day, and no paid tier lifts it.",
            "",
        ]

    if wpis["kind"] == "wrong-sender":
        czesci += [
            "## This is not the Basic auth shutdown",
            "",
            "Authentication worked. Do not change the authentication settings — "
            "the problem is the `From` address.",
            "",
            "1. Check what address the device or application puts in `From`.",
            "2. Check which mailbox the credentials belong to.",
            "3. If they differ, either set `From` to the authenticated mailbox, "
            "or grant that mailbox **Send As** on the address you want to use.",
            "",
            "This turns up most often after pointing a device at a shared or "
            "service mailbox and leaving the old From address in its settings.",
            "",
        ]

    if wpis["kind"] == "auth-refused":
        czesci += [
            "## If it cannot be turned back on",
            "",
            "Three options remain, and they differ more than they look:",
            "",
            "- **OAuth on the device** — check the exact model against "
            "[the compatibility list](../DEVICE-COMPATIBILITY.md). Several "
            "vendors have stated in writing that no firmware is coming for "
            "specific models.",
            "- **Direct Send** — free, but delivers only to recipients inside "
            "your own tenant, and needs a connector and a static IP.",
            "- **A relay that still accepts a username and password** — works "
            "for any recipient, and is three fields on the device.",
            "",
            "[The migration guide](../EXCHANGE-ONLINE-SMTP-AUTH.md) covers all "
            "of them, Graph API and paid relays included. ZeroSMTP is the "
            "third: free, no paid tier, 200 messages a day, and it sends from a "
            "shared `@msgwing.com` address rather than your own domain. If the "
            "from-address has to be yours, it is the wrong answer — the guide "
            "covers the others honestly.",
            "",
            "[Create a free account](https://msgwing.com) · "
            "[settings by printer brand](../PRINTERS.md) · "
            "[code examples in 19 languages](../CODE-EXAMPLES.md)",
            "",
        ]

    czesci += [
        "## Two things this is often confused with",
        "",
        "| Symptom | Actual cause |",
        "| --- | --- |",
        "| Connection times out; no authentication error ever appears | The "
        "network is blocking outbound SMTP. Cloud providers block port 25 and "
        "often 587 by default — see [troubleshooting](../TROUBLESHOOTING.md). |",
        "| `Certificate verify failed` / `unable to get local issuer "
        "certificate` | The device's trust store cannot validate the server "
        "certificate. Common on firmware predating current root CAs — see [the "
        "Canon Maxify MB2755 case](../DEVICE-CASE-STUDIES.md). |",
        "",
        *(["", f"**Source:** [Microsoft's own list of Exchange Online error "
           f"codes]({wpis['source']}). This entry was written from that "
           "documentation rather than from watching a machine fail, which is "
           "worth knowing when you compare it against what your hardware "
           "actually printed."] if wpis.get("source") else []),
        "",
        "## Related",
        "",
        "- [All SMTP AUTH error messages](../ERROR-MESSAGES.md)",
        "- [Which devices have OAuth firmware](../DEVICE-COMPATIBILITY.md)",
        "- [What breaks at the end of December 2026](../AFFECTED-SYSTEMS.md)",
        "",
        "Seeing a string that is not here? "
        "[Report it](https://github.com/msgwing/ZeroSMTP/issues/new/choose) with "
        "what produced it. Errors from real hardware are worth more than "
        "anything transcribed from documentation.",
        "",
        f"*Last reviewed {aktualizacja}.*",
        "",
    ]

    return "\n".join(czesci)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if anything is out of date instead of rewriting it")
    args = ap.parse_args()

    dane = json.loads(DANE.read_text(encoding="utf-8"))
    wpisy = dane["entries"]

    nieznane = {w["kind"] for w in wpisy} - RODZAJE
    if nieznane:
        print(f"Unknown kind values: {sorted(nieznane)}")
        return 1

    slugi = [w["slug"] for w in wpisy]
    if len(set(slugi)) != len(slugi):
        print("Duplicate slugs - one page would silently overwrite another.")
        return 1

    # Tytuly licza sie raz, po kolei, bo kazdy nastepny musi wiedziec, co juz
    # jest zajete. Inaczej dwa wpisy roznlace sie ostatnim slowem dostaja ten
    # sam tytul po skroceniu.
    # Najpierw naturalne skrocenie dla wszystkich, potem kolizje. Przypisywanie
    # po kolei dawalo wynik niesymetryczny: pierwszy wpis zajmowal tytul bez
    # wyroznika, drugi dostawal nawias - i strona o dzierzawie nie mowila
    # "Tenant", mimo ze to jedyne, co ja odroznia. Wyroznik dostaja wszyscy
    # uczestnicy kolizji albo nikt.
    naturalne = {w["slug"]: tytul(w) for w in wpisy}
    grupy = {}
    for slug, t in naturalne.items():
        grupy.setdefault(t, []).append(slug)
    kolidujace = {sl for grupa in grupy.values() if len(grupa) > 1 for sl in grupa}

    tytuly = {}
    for w in wpisy:
        if w["slug"] in kolidujace:
            tytuly[w["slug"]] = tytul(w, {naturalne[w["slug"]]})
        else:
            tytuly[w["slug"]] = naturalne[w["slug"]]

    za_dlugie = [w for w in wpisy if len(tytuly[w["slug"]]) > LIMIT_TYTULU]
    if za_dlugie:
        print(f"Titles over the {LIMIT_TYTULU}-character SEO budget:")
        for w in za_dlugie:
            print(f"  {len(tytuly[w['slug']])}: {tytuly[w['slug']]}")
        return 1

    # Bramka, ktorej tu nie bylo. Kontrola duplikatow istniala dla nazw plikow
    # i nie istniala dla tytulow, wiec dwie strony o 5.7.139 - jedna o skrzynce,
    # druga o dzierzawie - wyszly z identycznym tytulem. Wyszukiwarka czyta
    # duplikat tytulu jako powod, zeby pokazac tylko jedna z nich, a to sa dwa
    # rozne problemy z roznymi rozwiazaniami.
    licznik = {}
    for slug, t in tytuly.items():
        licznik.setdefault(t, []).append(slug)
    zdublowane = {t: sl for t, sl in licznik.items() if len(sl) > 1}
    if zdublowane:
        print("Duplicate titles - a search engine will show only one of them:")
        for t, sl in zdublowane.items():
            print(f"  {t!r}: {', '.join(sl)}")
        return 1

    wyjscia = {
        KATALOG / f"{w['slug']}.md": zbuduj(w, dane["updated"], tytuly[w["slug"]])
        for w in wpisy
    }

    # The overview table joins the same check/write loop as the pages, so the
    # index and the pages cannot get out of step - which is exactly what
    # happened when it was maintained by hand.
    przeglad = PRZEGLAD.read_text(encoding="utf-8")
    a = przeglad.index(POCZATEK)
    b = przeglad.index(KONIEC) + len(KONIEC)
    wyjscia[PRZEGLAD] = przeglad[:a] + zbuduj_indeks(wpisy) + przeglad[b:]

    istniejace = set(KATALOG.glob("*.md")) if KATALOG.exists() else set()
    osierocone = sorted(istniejace - set(wyjscia))

    def sciezka(p):
        return p.relative_to(KORZEN).as_posix()

    if args.check:
        rozne = [
            p for p, t in wyjscia.items()
            if not p.exists() or p.read_text(encoding="utf-8") != t
        ]
        if rozne or osierocone:
            for p in rozne:
                print(f"out of date: {sciezka(p)}")
            for p in osierocone:
                print(f"orphaned:    {sciezka(p)}")
            print("Run:  python tools/build-error-pages.py")
            return 1
        print(f"{len(wyjscia)} error pages match data/errors.json")
        return 0

    KATALOG.mkdir(parents=True, exist_ok=True)
    zapisane = 0
    for p, t in wyjscia.items():
        if not p.exists() or p.read_text(encoding="utf-8") != t:
            p.write_bytes(t.encode())
            zapisane += 1
    for p in osierocone:
        p.unlink()
        print(f"removed orphaned page: {sciezka(p)}")

    print(f"{zapisane} file(s) rewritten, {len(osierocone)} removed "
          f"({len(wpisy)} errors)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
