#!/usr/bin/env python3
"""Render one page per serverless/edge platform from data/platforms.json.

A different audience than tools/build-device-table.py or build-app-pages.py:
not a sysadmin with a printer, a developer deciding whether their deploy
target can even open a raw SMTP connection at all before they get anywhere
near ZeroSMTP's own settings. "Does net/tls work here" is a platform question
that has nothing to do with the December 2026 Basic auth shutdown - a
Cloudflare Worker or a Vercel Edge Function was never able to send SMTP in
the first place, shutdown or not.

Same contract as its three siblings: generated, `--check`ed in CI, orphans
removed, every field name traceable to the vendor's own current
documentation rather than recalled - and where that could not be confirmed
against a working primary source, the entry says so instead of guessing.

    python tools/build-platform-pages.py            # rewrite the pages
    python tools/build-platform-pages.py --check    # fail if anything would change
"""

import argparse
import json
import pathlib
import re
import sys

KORZEN = pathlib.Path(__file__).resolve().parent.parent
DANE = KORZEN / "data" / "platforms.json"
KATALOG = KORZEN / "docs" / "platforms"
INDEKS = KORZEN / "docs" / "PLATFORMS.md"

LIMIT_TYTULU = 48
MIN_TYTULU = 8

VERDICT_LABEL = {
    "works": "Works",
    "unconfirmed": "Unconfirmed",
    "depends on which runtime you picked": "Depends on the runtime",
}


def zbuduj(wpis, aktualizacja, t):
    etykieta = VERDICT_LABEL.get(wpis["verdict"], wpis["verdict"].capitalize())

    czesci = [
        "---",
        f'title: "{t}"',
        f'description: "{wpis["summary"]}"',
        "---",
        "",
        "<!-- BEGIN GENERATED PAGE -->",
        "<!-- Generated by tools/build-platform-pages.py from",
        "     data/platforms.json. Edit the JSON, not this file - CI rejects",
        "     the two disagreeing. -->",
        "",
        f"# {wpis['name']} and SMTP",
        "",
        f"**Runtime:** {wpis['runtime']}",
        "",
        f"**Verdict: {etykieta}.** {wpis['summary']}",
        "",
        "## What actually happens on this platform",
        "",
        wpis["detail"],
        "",
        "## The part worth reading twice",
        "",
        wpis["caveat"],
        "",
        "## If it works here",
        "",
        "The connection itself is the same as everywhere else: point at "
        "`mx.msgwing.com` on port 587 (STARTTLS) or 465 (SSL/TLS), "
        "authenticate with a username and password. Register at "
        "[msgwing.com](https://msgwing.com) first, then use the "
        "[Node.js/TypeScript example](../CODE-EXAMPLES.html) unmodified - "
        "nothing about running inside this platform changes the SMTP "
        "conversation itself, only whether the platform lets you open that "
        "connection in the first place.",
        "",
        "## Where this came from",
        "",
        f"Read off [{wpis['source_title']}]({wpis['source']}), "
        f"{wpis['name']}'s own documentation, checked {wpis['checked']} - "
        "rather than recalled. If that page and this one now disagree, that "
        "page is right and this one is out of date - "
        "[say so](https://github.com/msgwing/ZeroSMTP/issues/new/choose).",
        "",
        "## Related",
        "",
        "- [Other platforms](../PLATFORMS.md)",
        "- [Code examples in 19 languages](../CODE-EXAMPLES.md)",
        "- [SMTP AUTH error messages](../ERROR-MESSAGES.md)",
        "",
        f"*Last reviewed {aktualizacja}.*",
        "",
    ]

    return "\n".join(czesci)


INDEKS_TYTUL = "Can I send SMTP from a serverless platform?"
INDEKS_OPIS = ("Whether Cloudflare Workers, Vercel, Netlify and AWS Lambda "
               "let a function open a raw SMTP connection at all, before "
               "any ZeroSMTP setting comes into it.")


def zbuduj_indeks(wpisy, aktualizacja):
    w = [
        "---",
        f'title: "{INDEKS_TYTUL}"',
        f'description: "{INDEKS_OPIS}"',
        "---",
        "",
        "<!-- BEGIN GENERATED PAGE -->",
        "<!-- Generated by tools/build-platform-pages.py from",
        "     data/platforms.json. -->",
        "",
        "# Can I send SMTP from a serverless platform?",
        "",
        "A question that has nothing to do with the December 2026 Basic "
        "auth shutdown, and gets asked anyway: some serverless and edge "
        "runtimes cannot open a raw TCP socket at all, which means SMTP "
        "was never possible there regardless of what the mail server on "
        "the other end requires.",
        "",
        "| Platform | Runtime | Verdict |",
        "|---|---|---|",
    ]

    for e in wpisy:
        etykieta = VERDICT_LABEL.get(e["verdict"], e["verdict"].capitalize())
        w.append(f"| [{e['name']}](platforms/{e['slug']}.md) | {e['runtime']} | {etykieta} |")

    w += [
        "",
        "Each page names the exact API involved, quotes where that came "
        "from, and states plainly when something could not be confirmed "
        "rather than guessing which way it goes.",
        "",
        "## Related",
        "",
        "- [Code examples in 19 languages](CODE-EXAMPLES.md)",
        "- [Self-hosted applications](SELF-HOSTED.md)",
        "- [SMTP AUTH error messages](ERROR-MESSAGES.md)",
        "",
        f"*Last reviewed {aktualizacja}.*",
        "",
    ]

    return "\n".join(w)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                     help="exit 1 if anything is out of date instead of rewriting it")
    args = ap.parse_args()

    dane = json.loads(DANE.read_text(encoding="utf-8"))
    wpisy = dane["entries"]

    slugi = [w["slug"] for w in wpisy]
    if len(set(slugi)) != len(slugi):
        print("Duplicate slugs - one page would silently overwrite another.")
        return 1

    bez = [w["slug"] for w in wpisy
           if not w.get("source", "").startswith("https://")]
    if bez:
        print("Entries without a source URL - every claim has to be "
              "traceable to the vendor's own page:")
        for s in bez:
            print(f"  {s}")
        return 1

    bez_zastrzezen = [w["slug"] for w in wpisy if not w.get("caveat", "").strip()]
    if bez_zastrzezen:
        print("Entries without a caveat - a page with no honest limit is an "
              "advert:")
        for s in bez_zastrzezen:
            print(f"  {s}")
        return 1

    tytuly = {w["slug"]: f"{w['name']} and SMTP" for w in wpisy}

    zle = [s for s, t in tytuly.items()
           if not MIN_TYTULU <= len(t) <= LIMIT_TYTULU]
    if zle:
        print(f"Titles outside the {MIN_TYTULU}-{LIMIT_TYTULU} character "
              f"budget:")
        for s in zle:
            print(f"  {len(tytuly[s])}: {tytuly[s]}")
        return 1

    licznik = {}
    for s, t in tytuly.items():
        licznik.setdefault(t, []).append(s)
    zdublowane = {t: sl for t, sl in licznik.items() if len(sl) > 1}
    if zdublowane:
        print("Duplicate titles - a search engine will show only one of them:")
        for t, sl in zdublowane.items():
            print(f"  {t!r}: {', '.join(sl)}")
        return 1

    # Meta descriptions are the field Bing's Site Scan flagged twice today
    # (229 and a silently-broken one) - checked here so a future entry
    # cannot repeat either failure.
    zle_opis = [w["slug"] for w in wpisy if not 20 <= len(w["summary"]) <= 160]
    if zle_opis:
        print("Descriptions outside the 20-160 character budget:")
        for s in zle_opis:
            e = next(w for w in wpisy if w["slug"] == s)
            print(f"  {len(e['summary'])}: {e['summary']}")
        return 1

    if not 20 <= len(INDEKS_OPIS) <= 160:
        print(f"Index description is {len(INDEKS_OPIS)} characters, "
              f"outside the 20-160 budget: {INDEKS_OPIS}")
        return 1

    wyjscia = {
        KATALOG / f"{w['slug']}.md": zbuduj(w, dane["updated"], tytuly[w["slug"]])
        for w in wpisy
    }
    wyjscia[INDEKS] = zbuduj_indeks(wpisy, dane["updated"])

    powstana = {q.resolve() for q in wyjscia}
    martwe = []
    for p, t in wyjscia.items():
        for cel in re.findall(r"\]\(([^)#:]+\.md)\)", t):
            docelowy = (p.parent / cel)
            if not docelowy.exists() and docelowy.resolve() not in powstana:
                martwe.append(f"{p.relative_to(KORZEN).as_posix()} -> {cel}")
    if martwe:
        print("Links that resolve to nothing:")
        for m in martwe:
            print(f"  {m}")
        return 1

    istniejace = set(KATALOG.glob("*.md")) if KATALOG.exists() else set()
    osierocone = sorted(istniejace - set(wyjscia))

    def sciezka(p):
        return p.relative_to(KORZEN).as_posix()

    if args.check:
        rozne = [
            p for p, t in wyjscia.items()
            if not p.exists() or p.read_text(encoding="utf-8") != t
        ]
        if rozne or osierocone:
            for p in rozne:
                print(f"out of date: {sciezka(p)}")
            for p in osierocone:
                print(f"orphaned:    {sciezka(p)}")
            print("Run:  python tools/build-platform-pages.py")
            return 1
        print(f"{len(wyjscia)} platform pages match data/platforms.json")
        return 0

    KATALOG.mkdir(parents=True, exist_ok=True)
    zapisane = 0
    for p, t in wyjscia.items():
        if not p.exists() or p.read_text(encoding="utf-8") != t:
            p.write_bytes(t.encode())
            zapisane += 1
    for p in osierocone:
        p.unlink()
        print(f"removed orphaned page: {sciezka(p)}")

    print(f"{zapisane} file(s) rewritten, {len(osierocone)} removed "
          f"({len(wpisy)} platforms)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
