#!/usr/bin/env python3
"""Render docs/BLAST-RADIUS.md from data/blast-radius.json.

Nobody has published a number for how much of the world still points at
Microsoft 365 SMTP. Every article on the December 2026 shutdown says "many
systems will be affected", which is a shrug rather than a fact. GitHub code
search can put a floor under it, and a weekly series answers the question the
single number cannot: is anybody actually fixing this?

The page is careful about what the figure is, because a number that overstates
its case is a number that gets dismissed. It counts *files containing a
hostname*, not systems that will break.

    python tools/build-blast-radius.py            # rewrite the page
    python tools/build-blast-radius.py --check    # fail if it would change
"""

import argparse
import json
import pathlib
import sys

KORZEN = pathlib.Path(__file__).resolve().parent.parent
DANE = KORZEN / "data" / "blast-radius.json"
STRONA = KORZEN / "docs" / "BLAST-RADIUS.md"


def liczba(n):
    return "not counted" if n is None else f"{n:,}"


def zmiana(teraz, wtedy):
    """Percentage move, or None when either end is missing. A failed
    measurement must not render as a dramatic drop."""
    if teraz is None or wtedy is None or wtedy == 0:
        return None
    return (teraz - wtedy) / wtedy * 100.0


def buduj(dane):
    zapytania = dane["queries"]
    probki = sorted(dane["samples"], key=lambda s: s["date"])
    ostatnia = probki[-1]
    pierwsza = probki[0]

    najwieksza = max(
        (ostatnia["counts"].get(z["id"]) or 0 for z in zapytania), default=0)

    linie = [
        "---",
        'title: "How much public code breaks in December 2026"',
        'description: "A weekly count of public files on GitHub that still '
        'point at Microsoft 365 SMTP, and what the number does and does not '
        'mean."',
        "---",
        "",
        "<!-- Generated by tools/build-blast-radius.py from",
        "     data/blast-radius.json. Edit the JSON, not this file. -->",
        "",
        "# How much public code breaks in December 2026",
        "",
        f"At least **{najwieksza:,} public files on GitHub** still contain a "
        "Microsoft 365 SMTP hostname. Every one of them is a place where "
        "somebody wrote down a setting that stops working when Basic "
        "authentication is switched off by default at the end of December "
        "2026.",
        "",
        # The count of samples, not a promise about cadence. The page said
        # "re-measured every week" while the series held a single point,
        # and the first reader to check that would have been right to stop
        # believing the rest of it. The schedule is stated as a schedule.
        f"Measured {ostatnia['date']}. The measurement runs every Monday, and "
        f"{'the series below has ' + str(len(probki)) + ' sample' + ('' if len(probki) == 1 else 's') + ' so far' if len(probki) < 4 else 'the series below is the more interesting half'}: "
        "a single number says the problem is large, a series says whether "
        "anyone is fixing it.",
        "",
        "## Current count",
        "",
        "| Hostname | Public files | Change since first measurement |",
        "| --- | --- | --- |",
    ]

    for z in zapytania:
        teraz = ostatnia["counts"].get(z["id"])
        wtedy = pierwsza["counts"].get(z["id"])
        d = zmiana(teraz, wtedy)
        if d is None:
            ruch = "—"
        elif abs(d) < 0.5:
            ruch = "no meaningful change"
        else:
            ruch = f"{d:+.1f}%"
        linie.append(f"| `{z['label']}` | {liczba(teraz)} | {ruch} |")

    linie += [
        "",
        "The two are **not added together**: a single file can contain both "
        "hostnames, so a total would double-count.",
        "",
        "## What this number is",
        "",
        "Public files, indexed by GitHub code search, containing a Microsoft "
        "365 SMTP hostname.",
        "",
        "## What it is not",
        "",
        "**It is not a count of systems that will break.** The same file might "
        "be a live deployment, a configuration template, a tutorial, or a fork "
        "of one of those. Some of those repositories are abandoned. Some of "
        "the hostnames sit in commented-out lines.",
        "",
        "This distinction is not modesty. A figure that claims more than it "
        "can support is a figure the first informed reader throws out, and "
        "then the number stops being useful to anybody. What can be defended "
        "is this: **each of these files is a place where a working SMTP "
        "setting was written down, and that setting is on a clock.**",
        "",
        "It is also a floor rather than a ceiling. It sees only public "
        "repositories, only default branches, and only what GitHub has "
        "indexed. Private repositories, internal configuration management, "
        "and the printer control panel in the corner of the office — which is "
        "where most of the real exposure lives — are all invisible to it.",
        "",
        "## Method",
        "",
        "One authenticated GitHub code search per query, weekly, recording the "
        "reported total:",
        "",
    ]

    for z in zapytania:
        linie += [f"- **`{z['label']}`** — `{z['q']}`  ", f"  {z['note']}", ""]

    linie += [
        "GitHub's totals are approximate and move slightly between identical "
        "queries, so small week-to-week changes mean nothing. A query that "
        "times out is recorded as `null`, never as zero — a failed "
        "measurement rendered as a drop would look like progress that never "
        "happened.",
        "",
        "The raw data is "
        "[`data/blast-radius.json`](https://github.com/msgwing/ZeroSMTP/blob/main/data/blast-radius.json), "
        "and every measurement is a commit, so the history can be checked "
        "rather than taken on trust.",
        "",
        "## The series",
        "",
        "| Date | " + " | ".join(f"`{z['label']}`" for z in zapytania) + " |",
        "| --- | " + " | ".join("---" for _ in zapytania) + " |",
    ]

    for p in reversed(probki):
        komorki = " | ".join(liczba(p["counts"].get(z["id"])) for z in zapytania)
        linie.append(f"| {p['date']} | {komorki} |")

    linie += [
        "",
        "## Reusing this",
        "",
        "The figure and the data are free to cite, quote and republish under "
        "the repository's MIT licence — a link back is appreciated but not "
        "required. If you are writing about the December 2026 deadline and "
        "need a defensible number, this is one, along with everything above "
        "about its limits.",
        "",
        "## If one of these files is yours",
        "",
        "- [What the error will look like](ERROR-MESSAGES.md) when it starts "
        "failing",
        "- [Whether your hardware has an OAuth path](DEVICE-COMPATIBILITY.md), "
        "with a link to every vendor statement",
        "- [Every migration option](EXCHANGE-ONLINE-SMTP-AUTH.md), including "
        "the ones that are not this project",
        # `npx zerosmtp-check` is back as of 2026-08-22: the package is
        # published (1.0.0, with provenance) and the registry returns 200.
        # It was pulled from this list while the package 404'd, and the
        # correction was made twice on the generated page before anybody
        # noticed the page is generated and this script was putting it
        # straight back. If it ever 404s again, fix it here, not there.
        "- `npx zerosmtp-check` — no install; checks in two seconds whether "
        "your network even lets SMTP out, before you assume it is the "
        "credentials. `./check-connection.sh` and `check-connection.ps1` in "
        "the repository do the same without Node.",
        "",
    ]

    return "\n".join(linie)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sync", action="store_true",
                    help="pull the accumulated series from the status branch first")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if args.sync:
        # Seria rosnie na galezi `status`, bo `main` jest chroniony i workflow
        # nie moze do niego pisac - to jest opisane w blast-radius.yml i jest
        # celowe. Skutek uboczny nie byl celowy: strona buduje sie z ziarna na
        # `main`, wiec pokazywala jedna probke z 2026-08-16, podczas gdy seria
        # miala juz dwie i druga byla ciekawsza - 24 960 -> 25 728 w osiem dni.
        # Jedyny unikalny zbior danych tego projektu byl niewidoczny.
        import urllib.request
        adres = ("https://raw.githubusercontent.com/msgwing/ZeroSMTP/"
                 "status/blast-radius-samples.json")
        with urllib.request.urlopen(adres, timeout=25) as o:
            zdalne = json.load(o)
        lokalne = json.loads(DANE.read_text(encoding="utf-8"))
        stare = len(lokalne.get("samples", []))
        lokalne["samples"] = sorted(zdalne["samples"], key=lambda s: s["date"])
        DANE.write_text(json.dumps(lokalne, indent=2, ensure_ascii=False) + chr(10),
                        encoding="utf-8", newline=chr(10))
        print(f"synced samples from status: {stare} -> {len(lokalne['samples'])}")

    dane = json.loads(DANE.read_text(encoding="utf-8"))

    if not dane.get("samples"):
        print("No samples in data/blast-radius.json")
        return 1

    znane = {z["id"] for z in dane["queries"]}
    for p in dane["samples"]:
        nieznane = set(p["counts"]) - znane
        if nieznane:
            print(f"Sample {p['date']} has counts for unknown queries: "
                  f"{sorted(nieznane)}")
            return 1

    nowa = buduj(dane)

    if args.check:
        if not STRONA.exists() or STRONA.read_text(encoding="utf-8") != nowa:
            print(f"{STRONA.name} is out of date. Run:")
            print("  python tools/build-blast-radius.py")
            return 1
        print(f"{STRONA.name} matches data/blast-radius.json "
              f"({len(dane['samples'])} samples)")
        return 0

    if STRONA.exists() and STRONA.read_text(encoding="utf-8") == nowa:
        print(f"{STRONA.name} already up to date")
        return 0

    STRONA.write_bytes(nowa.encode())
    print(f"{STRONA.name} rewritten ({len(dane['samples'])} samples)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
