#!/usr/bin/env python3
"""Render one page per SMTP error string from data/errors.json.

An error string is the highest-intent query this project can rank for.
Somebody pasting `535 5.7.139 SmtpClientAuthentication is disabled for the
Tenant` into a search box is broken at that moment and is looking for exactly
this - there is no ambiguity about what they want. docs/ERROR-MESSAGES.md
covers six distinct strings on one page, and a page covering six loses each of
them to a page covering one.

Same contract as tools/build-device-table.py: generated, `--check`ed in CI,
orphans removed.

    python tools/build-error-pages.py            # rewrite the pages
    python tools/build-error-pages.py --check    # fail if anything would change
"""

import argparse
import json
import pathlib
import sys

KORZEN = pathlib.Path(__file__).resolve().parent.parent
DANE = KORZEN / "data" / "errors.json"
KATALOG = KORZEN / "docs" / "errors"

# jekyll-seo-tag appends " | ZeroSMTP"; docs/_config.yml documents ~50
# characters for the part before it.
LIMIT_TYTULU = 48

RODZAJE = {"auth-refused", "no-credentials", "wrong-sender"}

# Three of the four causes are still reversible before the end of December
# 2026. Saying "you must migrate" to somebody a settings change would have
# fixed is bad advice, and it happens to be the advice that suits us - which
# is exactly why it is written down here once and reused.
PRZYCZYNY = [
    ("An admin disabled SMTP AUTH for the tenant or the mailbox",
     "Yes — until the end of December 2026"),
    ("**Security Defaults**, on by default for recently created tenants",
     "Yes, but it disables more than SMTP and turning it off weakens the tenant"),
    ("A **Conditional Access** policy blocking legacy authentication",
     "Yes, by scoping the policy — but it is usually deliberate, so ask why it exists"),
    ("The **end-of-December-2026 default change**",
     "No"),
]


def tytul(wpis):
    """The code alone is what people paste and what should win the match."""
    pelny = f"{wpis['code']} {wpis['message']}"
    if len(pelny) <= LIMIT_TYTULU:
        return pelny

    slowa = wpis["message"].split()
    while slowa:
        slowa.pop()
        skrocony = f"{wpis['code']} {' '.join(slowa)}"
        if slowa and len(skrocony) <= LIMIT_TYTULU:
            return skrocony

    return wpis["code"]


def zbuduj(wpis, aktualizacja):
    pelny = f"{wpis['code']} {wpis['message']}"

    czesci = [
        "---",
        f"title: {json.dumps(tytul(wpis))}",
        f"description: {json.dumps(f'What {pelny} means, whether it can still be turned back on, and what to do if it cannot.')}",
        "---",
        "",
        "<!-- Generated by tools/build-error-pages.py from data/errors.json.",
        "     Edit the JSON, not this file - CI rejects the two disagreeing. -->",
        "",
        f"# {pelny}",
        "",
        "```",
        pelny,
        "```",
        "",
        wpis["meaning"],
        "",
    ]

    if wpis["kind"] == "auth-refused":
        czesci += [
            "**This does not mean your password is wrong.** Nothing about the "
            "credentials changed; the method used to present them was switched "
            "off.",
            "",
            "## Which of the four causes is yours",
            "",
            "Basic auth for SMTP AUTH gets refused in four situations, and the "
            "message the client shows is identical in all of them. Which one you "
            "are in decides whether this is a setting or a migration:",
            "",
            "| Cause | Can you turn it back on? |",
            "| --- | --- |",
            *[f"| {c} | {r} |" for c, r in PRZYCZYNY],
            "",
            "Before the end of December 2026 the first three are the likely "
            "answer, and the fix may be a checkbox rather than a project. After "
            "it, re-enabling stops being an option.",
            "",
            "## Find out which mailboxes are affected",
            "",
            "[`Find-SmtpAuthExposure.ps1`](https://github.com/msgwing/ZeroSMTP/blob/main/Find-SmtpAuthExposure.ps1) "
            "answers this for your own tenant. It is read-only.",
            "",
            "It exists because the one-liner everybody reaches for —",
            "`Get-CASMailbox | Where SmtpClientAuthenticationDisabled -eq $false` "
            "— **misses every mailbox that inherits the tenant setting** rather "
            "than carrying its own, and can therefore report zero on a tenant "
            "that is fully exposed. The script counts all three states "
            "separately.",
            "",
        ]

    if wpis.get("wrappers"):
        czesci += [
            "## The same error in other clothes",
            "",
            "Libraries and device firmware rarely pass the server's message "
            "through unchanged. These are the same refusal:",
            "",
            *[f"- {w}" for w in wpis["wrappers"]],
            "",
            "Kyocera MFPs report it as **send error 1102** / `0x1102`, which "
            "looks like a hardware fault and is not one.",
            "",
        ]

    if wpis["kind"] == "no-credentials":
        czesci += [
            "## Check this before assuming it is the Basic auth shutdown",
            "",
            "This one is worth ruling out cheaply, because the fix is usually "
            "local:",
            "",
            "1. Does the device's SMTP configuration have an authentication "
            "checkbox, and is it off?",
            "2. Was this device previously relaying anonymously through an "
            "internal server that has since been retired or repointed?",
            "3. Is it sending `AUTH` after `MAIL FROM`? Some older firmware "
            "does, and Microsoft 365 will not accept it.",
            "",
            "If authentication is genuinely configured and still refused, you "
            "are looking at "
            "[`535 5.7.139`](535-5-7-139-basic-authentication-is-disabled.md) "
            "instead.",
            "",
        ]

    if wpis["kind"] == "wrong-sender":
        czesci += [
            "## This is not the Basic auth shutdown",
            "",
            "Authentication worked. Do not change the authentication settings — "
            "the problem is the `From` address.",
            "",
            "1. Check what address the device or application puts in `From`.",
            "2. Check which mailbox the credentials belong to.",
            "3. If they differ, either set `From` to the authenticated mailbox, "
            "or grant that mailbox **Send As** on the address you want to use.",
            "",
            "This turns up most often after pointing a device at a shared or "
            "service mailbox and leaving the old From address in its settings.",
            "",
        ]

    if wpis["kind"] == "auth-refused":
        czesci += [
            "## If it cannot be turned back on",
            "",
            "Three options remain, and they differ more than they look:",
            "",
            "- **OAuth on the device** — check the exact model against "
            "[the compatibility list](../DEVICE-COMPATIBILITY.md). Several "
            "vendors have stated in writing that no firmware is coming for "
            "specific models.",
            "- **Direct Send** — free, but delivers only to recipients inside "
            "your own tenant, and needs a connector and a static IP.",
            "- **A relay that still accepts a username and password** — works "
            "for any recipient, and is three fields on the device.",
            "",
            "[The migration guide](../EXCHANGE-ONLINE-SMTP-AUTH.md) covers all "
            "of them, Graph API and paid relays included. ZeroSMTP is the "
            "third: free, no paid tier, 200 messages a day, and it sends from a "
            "shared `@msgwing.com` address rather than your own domain. If the "
            "from-address has to be yours, it is the wrong answer — the guide "
            "covers the others honestly.",
            "",
            "[Create a free account](https://msgwing.com) · "
            "[settings by printer brand](../PRINTERS.md) · "
            "[code examples in 19 languages](../CODE-EXAMPLES.md)",
            "",
        ]

    czesci += [
        "## Two things this is often confused with",
        "",
        "| Symptom | Actual cause |",
        "| --- | --- |",
        "| Connection times out; no authentication error ever appears | The "
        "network is blocking outbound SMTP. Cloud providers block port 25 and "
        "often 587 by default — see [troubleshooting](../TROUBLESHOOTING.md). |",
        "| `Certificate verify failed` / `unable to get local issuer "
        "certificate` | The device's trust store cannot validate the server "
        "certificate. Common on firmware predating current root CAs — see [the "
        "Canon Maxify MB2755 case](../DEVICE-CASE-STUDIES.md). |",
        "",
        "## Related",
        "",
        "- [All SMTP AUTH error messages](../ERROR-MESSAGES.md)",
        "- [Which devices have OAuth firmware](../DEVICE-COMPATIBILITY.md)",
        "- [What breaks at the end of December 2026](../AFFECTED-SYSTEMS.md)",
        "",
        "Seeing a string that is not here? "
        "[Report it](https://github.com/msgwing/ZeroSMTP/issues/new/choose) with "
        "what produced it. Errors from real hardware are worth more than "
        "anything transcribed from documentation.",
        "",
        f"*Last reviewed {aktualizacja}.*",
        "",
    ]

    return "\n".join(czesci)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if anything is out of date instead of rewriting it")
    args = ap.parse_args()

    dane = json.loads(DANE.read_text(encoding="utf-8"))
    wpisy = dane["entries"]

    nieznane = {w["kind"] for w in wpisy} - RODZAJE
    if nieznane:
        print(f"Unknown kind values: {sorted(nieznane)}")
        return 1

    slugi = [w["slug"] for w in wpisy]
    if len(set(slugi)) != len(slugi):
        print("Duplicate slugs - one page would silently overwrite another.")
        return 1

    za_dlugie = [w for w in wpisy if len(tytul(w)) > LIMIT_TYTULU]
    if za_dlugie:
        print(f"Titles over the {LIMIT_TYTULU}-character SEO budget:")
        for w in za_dlugie:
            print(f"  {len(tytul(w))}: {tytul(w)}")
        return 1

    wyjscia = {
        KATALOG / f"{w['slug']}.md": zbuduj(w, dane["updated"]) for w in wpisy
    }

    istniejace = set(KATALOG.glob("*.md")) if KATALOG.exists() else set()
    osierocone = sorted(istniejace - set(wyjscia))

    def sciezka(p):
        return p.relative_to(KORZEN).as_posix()

    if args.check:
        rozne = [
            p for p, t in wyjscia.items()
            if not p.exists() or p.read_text(encoding="utf-8") != t
        ]
        if rozne or osierocone:
            for p in rozne:
                print(f"out of date: {sciezka(p)}")
            for p in osierocone:
                print(f"orphaned:    {sciezka(p)}")
            print("Run:  python tools/build-error-pages.py")
            return 1
        print(f"{len(wyjscia)} error pages match data/errors.json")
        return 0

    KATALOG.mkdir(parents=True, exist_ok=True)
    zapisane = 0
    for p, t in wyjscia.items():
        if not p.exists() or p.read_text(encoding="utf-8") != t:
            p.write_bytes(t.encode())
            zapisane += 1
    for p in osierocone:
        p.unlink()
        print(f"removed orphaned page: {sciezka(p)}")

    print(f"{zapisane} file(s) rewritten, {len(osierocone)} removed "
          f"({len(wpisy)} errors)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
