#!/usr/bin/env python3
"""Render one page per library error string from data/clients.json.

tools/build-error-pages.py covers what the *server* said. This covers what the
*library* said instead, which is usually not the same sentence and is usually
the one that gets pasted into a search box.

Somebody whose WordPress site stopped sending mail does not see
`535 5.7.139 SmtpClientAuthentication is disabled for the Tenant`. They see
`SMTP connect() failed.` - six words that name no code, no tenant and no
cause, and that have been the same six words for every SMTP failure since
2011. They search for those six words. The page that answers them has to
contain those six words.

That is the same argument tools/build-error-pages.py makes for splitting one
overview page into six, applied one layer up. data/errors.json already carries
a `wrappers` field describing how each library reshapes the message - but it
carries it *inside* the server-error page, which is the arrangement that
generator's own docstring calls the losing one.

    python tools/build-client-error-pages.py            # rewrite the pages
    python tools/build-client-error-pages.py --check    # fail if out of date
"""

import argparse
import json
import pathlib
import sys

KORZEN = pathlib.Path(__file__).resolve().parent.parent
DANE = KORZEN / "data" / "clients.json"
BLEDY = KORZEN / "data" / "errors.json"
KATALOG = KORZEN / "docs" / "clients"
INDEKS = KORZEN / "docs" / "LIBRARY-ERRORS.md"

# jekyll-seo-tag appends " | ZeroSMTP"; docs/_config.yml documents ~50
# characters for the part before it. Same budget as the sibling generator.
LIMIT_TYTULU = 48

# Ponizej tego tytul nie niesie ani nazwy biblioteki, ani komunikatu.
MIN_TYTULU = 8


def tytul(wpis):
    """The library name plus its own message, trimmed from the end.

    The library name has to lead: `SMTP connect() failed.` on its own is
    ambiguous across half the PHP ecosystem, and a title that does not say
    WordPress will not be clicked by somebody whose WordPress site is down.
    """
    # curl drukuje wlasna nazwe na poczatku komunikatu. Doklejenie prefiksu
    # dalo "curl: curl: (67) Login denied" - zajakniecie, ktore czyta sie jak
    # usterka generatora, bo nia jest.
    if wpis["message"].lower().startswith(wpis["client"].lower() + ":"):
        return wpis["message"]

    t = f"{wpis['client']}: {wpis['message']}"
    if len(t) <= LIMIT_TYTULU:
        return t

    # Wiele z tych komunikatow ma wlasny naglowek przed dwukropkiem -
    # `SmtpException:`, `SMTP Error:` - i to on jest czescia, ktora ludzie
    # wklejaja. Ciecie po slowach zatrzymalo sie na "The SMTP", co nie jest
    # niczyim zapytaniem. Naglowek probujemy pierwszy.
    if ":" in wpis["message"]:
        naglowek = f"{wpis['client']}: {wpis['message'].split(':', 1)[0]}"
        if len(naglowek) <= LIMIT_TYTULU:
            return naglowek

    slowa = wpis["message"].split()
    while slowa and len(f"{wpis['client']}: {' '.join(slowa)}") > LIMIT_TYTULU:
        slowa.pop()
    return f"{wpis['client']}: {' '.join(slowa)}"


def zbuduj(wpis, blad, aktualizacja, t):
    plik = f"../errors/{wpis['server_slug']}.md"
    # Backticks, not !r: Python's repr() picks its quote character based on
    # what the string itself contains, so a message holding a single quote
    # (python-smtplib's does, from its own b'...' byte-string repr) comes back
    # wrapped in *double* quotes - which then broke the YAML front matter
    # below, since that quote landed unescaped inside another double-quoted
    # scalar. Every message here is checked clean of backticks already.
    opis = (
        f"{wpis['client']} reports `{wpis['message']}` when Microsoft 365 "
        f"refuses SMTP AUTH. What the server actually sent, how to make "
        f"{wpis['client']} print it, and what to do about it."
    )

    czesci = [
        "---",
        f'title: "{t}"',
        f'description: "{opis}"',
        "---",
        "",
        "<!-- BEGIN GENERATED PAGE -->",
        "<!-- Generated by tools/build-client-error-pages.py from",
        "     data/clients.json. Edit the JSON, not this file - CI rejects",
        "     the two disagreeing. -->",
        "",
        f"# {wpis['client']}: `{wpis['message']}`",
        "",
        f"**That is not the error. It is {wpis['client']}'s summary of one.**",
        "",
        wpis["hides"],
        "",
        "This matters because the summary is the same regardless of cause, and "
        "the server's line is not. One of them tells you whether you have "
        "days or minutes.",
        "",
        "## The line the server actually sent",
        "",
        f"> `{blad['message']}`",
        "",
        blad["meaning"],
        "",
        f"[Everything about this error]({plik}) — what causes it, which of "
        "the causes are still reversible, and how long each one has.",
        "",
        f"## How to make {wpis['client']} show it",
        "",
        "Do this before changing any setting. A guess costs an hour; the "
        "server's own sentence costs one line.",
        "",
        wpis["reveal"],
        "",
        "## What to do once you can read it",
        "",
        "The server's line decides, not the library's. Two cases, and they "
        "are not close:",
        "",
        "- **An admin, Security Defaults or a Conditional Access policy "
        "turned SMTP AUTH off.** Reversible today, and it is a tenant "
        "setting, not a code change. Nothing in "
        f"{wpis['client']} needs touching.",
        # Corrected 2026-08-29 against Microsoft's own post of 2026-01-27:
        # "SMTP AUTH Basic Authentication will be disabled by default for
        # existing tenants. Administrators will still be able to enable it if
        # needed." Calling that irreversible was wrong, and it contradicted
        # docs/EXCHANGE-ONLINE-SMTP-AUTH.md, which had it right all along.
        "- **It is the end-of-December-2026 default change.** Switched off by "
        "default on existing tenants. An administrator can re-enable it, so "
        "this is a reprieve rather than a fix — and Microsoft announces the "
        "*final* removal date in the second half of 2027. If you do not "
        "administer the tenant, that reprieve is not yours to take.",
        "",
        f"[Which one you are looking at]({plik}) is decided by the exact "
        "string, which is why getting it printed comes first.",
        "",
        "## If re-enabling it is not something you can do",
        "",
        f"ZeroSMTP is a free SMTP relay that accepts the credentials "
        f"{wpis['client']} already sends. It is a host, a port and a "
        "username — no OAuth flow, no app registration, no code path that "
        "does not exist yet in the version you are running.",
        "",
        # Etykieta idzie po ekosystemie, nie po bibliotece. Dla WordPressa
        # przyklad jest skryptem PHP, a zmiana dzieje sie w ustawieniach
        # wtyczki - "przyklad WordPressa" obiecywalby cos, czego tam nie ma.
        f"[Working {wpis['ecosystem']} example](../../{wpis['example']}) — "
        "the whole change is the connection settings.",
        "",
        "[Register for free](https://msgwing.com)",
        "",
        "## Related",
        "",
        f"- [The server error behind this one]({plik})",
        "- [All library error messages](../LIBRARY-ERRORS.md)",
        "- [All SMTP AUTH error messages](../ERROR-MESSAGES.md)",
        "- [What breaks at the end of December 2026](../AFFECTED-SYSTEMS.md)",
        "",
        f"Your library prints something else? "
        f"[Send the exact string](https://github.com/msgwing/ZeroSMTP/issues/"
        f"new?template=error-string.yml) and what produced it. A message "
        "copied from a real failure is worth more than one transcribed from "
        "documentation.",
        "",
        f"*Last reviewed {aktualizacja}.*",
        "",
    ]

    return "\n".join(czesci)


def zbuduj_indeks(wpisy, bledy, aktualizacja):
    wiersze = [
        "---",
        'title: "Library error messages"',
        'description: "What PHPMailer, WordPress, Nodemailer, Python '
        'smtplib, curl and .NET print when Microsoft 365 refuses SMTP AUTH - '
        'and the server line each of them hides."',
        "---",
        "",
        "<!-- BEGIN GENERATED PAGE -->",
        "<!-- Generated by tools/build-client-error-pages.py from",
        "     data/clients.json. Edit the JSON, not this file. -->",
        "",
        "# What your library says, and what the server said",
        "",
        "Almost no library shows you the refusal. It catches the server's "
        "line, throws away everything except the fact that something failed, "
        "and prints a sentence of its own — the same sentence it has printed "
        "for every SMTP failure for a decade.",
        "",
        "So the message you are searching for is not the message that "
        "explains anything. This table connects the two.",
        "",
        "| Your library prints | The server actually said |",
        "|---|---|",
    ]

    for w in wpisy:
        b = bledy[w["server_slug"]]
        wiersze.append(
            f"| [`{w['message']}`](clients/{w['slug']}.md)<br>{w['ecosystem']} "
            f"· {w['client']} | [`{b['message']}`](errors/{w['server_slug']}.md) |"
        )

    wiersze += [
        "",
        "## Why this is worth a table",
        "",
        "Three of the four things that produce these errors are reversible "
        "by anybody with tenant rights. The fourth is the "
        "end-of-December-2026 default change, and an administrator can undo "
        "that one too — until Microsoft names the final removal date, which "
        "it says it will do in the second half of 2027.",
        "",
        "The library's message cannot tell them apart. The server's line "
        "always can. Every page above starts with how to make your library "
        "print it.",
        "",
        "## Related",
        "",
        "- [All SMTP AUTH error messages](ERROR-MESSAGES.md)",
        "- [Which devices have OAuth firmware](DEVICE-COMPATIBILITY.md)",
        "- [What breaks at the end of December 2026](AFFECTED-SYSTEMS.md)",
        "",
        "Missing your library? "
        "[Send the exact string](https://github.com/msgwing/ZeroSMTP/issues/"
        "new?template=error-string.yml) and what produced it.",
        "",
        f"*Last reviewed {aktualizacja}.*",
        "",
    ]

    return "\n".join(wiersze)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if anything is out of date instead of rewriting it")
    args = ap.parse_args()

    dane = json.loads(DANE.read_text(encoding="utf-8"))
    wpisy = dane["entries"]
    bledy = {
        w["slug"]: w
        for w in json.loads(BLEDY.read_text(encoding="utf-8"))["entries"]
    }

    # Kazda strona cytuje linie serwera z errors.json. Slug, ktorego tam nie
    # ma, dalby strone cytujaca pustke i link donikad - a link donikad na
    # stronie, ktora ma kogos przekonac, jest gorszy niz brak strony.
    brakujace = [w["slug"] for w in wpisy if w["server_slug"] not in bledy]
    if brakujace:
        print("server_slug not found in data/errors.json:")
        for s in brakujace:
            print(f"  {s}")
        return 1

    # Przyklad jest jedynym miejscem, gdzie strona mowi "zrob tak" zamiast
    # "tak jest". Martwy odnosnik psuje dokladnie ten jeden akapit.
    braki = [w["example"] for w in wpisy if not (KORZEN / w["example"]).exists()]
    if braki:
        print("example files that do not exist:")
        for s in braki:
            print(f"  {s}")
        return 1

    slugi = [w["slug"] for w in wpisy]
    if len(set(slugi)) != len(slugi):
        print("Duplicate slugs - one page would silently overwrite another.")
        return 1

    tytuly = {w["slug"]: tytul(w) for w in wpisy}

    # Bramka pilnowala tylko gornej granicy i przepuscila tytul "Python
    # `smtplib`: " - komunikat scieto do zera, bo sama nazwa klienta zjadla
    # budzet. Za dlugi tytul wyglada niechlujnie; pusty nie mowi nikomu, o
    # czym jest strona, i jest gorszy. Limit ma dwa konce.
    puste = [s for s, t in tytuly.items()
             if len(t.rstrip().rstrip(":").strip()) < MIN_TYTULU]
    if puste:
        print("Titles trimmed away to nothing - the client name has no room "
              "left for the message:")
        for s in puste:
            print(f"  {s}: {tytuly[s]!r}")
        return 1

    za_dlugie = [s for s, t in tytuly.items() if len(t) > LIMIT_TYTULU]
    if za_dlugie:
        print(f"Titles over the {LIMIT_TYTULU}-character SEO budget:")
        for s in za_dlugie:
            print(f"  {len(tytuly[s])}: {tytuly[s]}")
        return 1

    # Ta bramka istnieje, bo brak jej w generatorze bledow kosztowal dwie
    # strony o 5.7.139 z identycznym tytulem. Tu ryzyko jest wyzsze: dwie
    # biblioteki PHP moga drukowac to samo zdanie.
    licznik = {}
    for s, t in tytuly.items():
        licznik.setdefault(t, []).append(s)
    zdublowane = {t: sl for t, sl in licznik.items() if len(sl) > 1}
    if zdublowane:
        print("Duplicate titles - a search engine will show only one of them:")
        for t, sl in zdublowane.items():
            print(f"  {t!r}: {', '.join(sl)}")
        return 1

    wyjscia = {
        KATALOG / f"{w['slug']}.md": zbuduj(
            w, bledy[w["server_slug"]], dane["updated"], tytuly[w["slug"]]
        )
        for w in wpisy
    }
    wyjscia[INDEKS] = zbuduj_indeks(wpisy, bledy, dane["updated"])

    istniejace = set(KATALOG.glob("*.md")) if KATALOG.exists() else set()
    osierocone = sorted(istniejace - set(wyjscia))

    def sciezka(p):
        return p.relative_to(KORZEN).as_posix()

    if args.check:
        rozne = [
            p for p, t in wyjscia.items()
            if not p.exists() or p.read_text(encoding="utf-8") != t
        ]
        if rozne or osierocone:
            for p in rozne:
                print(f"out of date: {sciezka(p)}")
            for p in osierocone:
                print(f"orphaned:    {sciezka(p)}")
            print("Run:  python tools/build-client-error-pages.py")
            return 1
        print(f"{len(wyjscia)} library pages match data/clients.json")
        return 0

    KATALOG.mkdir(parents=True, exist_ok=True)
    zapisane = 0
    for p, t in wyjscia.items():
        if not p.exists() or p.read_text(encoding="utf-8") != t:
            p.write_bytes(t.encode())
            zapisane += 1
    for p in osierocone:
        p.unlink()
        print(f"removed orphaned page: {sciezka(p)}")

    print(f"{zapisane} file(s) rewritten, {len(osierocone)} removed "
          f"({len(wpisy)} libraries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
