#!/usr/bin/env python3
"""Embed data/errors.json into the zerosmtp-check package as errors.js.

zerosmtp-check has no dependencies and must keep having none: a diagnostic
that needs `npm install` is useless on the machine where mail is already
broken. So the error corpus is compiled in rather than fetched, and this
script is the only thing allowed to write that file.

Same contract as tools/build-device-table.py and tools/build-error-pages.py:
generated, --check'ed in CI, never hand-edited. A generated file that somebody
corrects by hand gets overwritten and ships the wrong thing to production,
which has already happened here once.

    python tools/build-cli-errors.py            # rewrite
    python tools/build-cli-errors.py --check    # fail if it would change
"""

import argparse
import json
import pathlib
import re
import sys

# Microsoft documents most of these codes without the SMTP reply code in
# front - they publish "5.7.134", not "550 5.7.134". Splitting on a space
# assumed a reply code was always there and would raise on the first entry
# that had none, so the enhanced part is matched rather than positioned.
ENHANCED = re.compile(r"\d\.\d\.\d{1,3}")

KORZEN = pathlib.Path(__file__).resolve().parent.parent
DANE = KORZEN / "data" / "errors.json"
CEL = KORZEN / "packages" / "zerosmtp-check" / "errors.js"

# Panel codes that are the same refusal wearing a hardware costume. These come
# from docs/errors/ where they are already published; this is not a new claim.
# A technician reading 1102 off a Kyocera panel has no way to connect it to a
# tenant setting, and that gap is the reason this mode exists at all.
KODY_URZADZEN = {
    "1102": {
        "vendor": "Kyocera",
        "note": "Kyocera MFPs report an SMTP AUTH refusal as send error 1102 "
                "(also shown as 0x1102). It looks like a hardware fault and is "
                "not one - the device is being refused by the mail server.",
        "kind": "auth-refused",
    },
    "027-779": {
        "vendor": "Xerox",
        "note": "Xerox WorkCentre 7328/7335/7345/7346 devices report fault "
                "code 027-779 when SMTP authentication fails. Check the Scan "
                "to E-mail login and SMTP server settings before treating it "
                "as a hardware fault.",
        "kind": "auth-refused",
    },
}


def zbuduj() -> str:
    dane = json.loads(DANE.read_text(encoding="utf-8"))
    wpisy = [
        {
            "code": w["code"],
            "enhanced": ENHANCED.search(w["code"]).group(0),
            "message": w["message"],
            "kind": w["kind"],
            "scope": w["scope"],
            "meaning": w["meaning"],
            "slug": w["slug"],
        }
        for w in dane["entries"]
    ]
    return (
        "// Generated by tools/build-cli-errors.py from data/errors.json.\n"
        "// Do not edit. Run the generator; the diff is the review.\n"
        "\n"
        f"export const ERRORS = {json.dumps(wpisy, indent=2, ensure_ascii=False)};\n"
        "\n"
        f"export const DEVICE_CODES = {json.dumps(KODY_URZADZEN, indent=2, ensure_ascii=False)};\n"
    )


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    a = p.parse_args()

    nowy = zbuduj()
    stary = CEL.read_text(encoding="utf-8") if CEL.exists() else None

    if a.check:
        if stary != nowy:
            print(f"{CEL.relative_to(KORZEN)} is out of date. "
                  f"Run: python tools/build-cli-errors.py", file=sys.stderr)
            return 1
        print(f"{CEL.relative_to(KORZEN)} matches data/errors.json")
        return 0

    CEL.write_text(nowy, encoding="utf-8", newline="\n")
    print(f"wrote {CEL.relative_to(KORZEN)} - "
          f"{len(json.loads(DANE.read_text(encoding='utf-8'))['entries'])} errors, "
          f"{len(KODY_URZADZEN)} device codes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
