#!/usr/bin/env python3
"""Render one page per self-hosted application from data/apps.json.

Measured 2026-08-27: Immich (112k stars), Netdata (80k), Vaultwarden (66k),
Gitea (57k), Jellyfin (56k), Paperless-ngx (44k), Portainer (38k),
changedetection.io (33k), Wiki.js (28k) and Authelia (28k) had **zero**
occurrences anywhere in docs/ or data/. Uptime Kuma, Home Assistant, Grafana,
Zabbix and Nextcloud were covered; the rest of the self-hosted world was not.

These applications are the population this relay's two limits do not hurt.
They send a handful of messages a month, to the operator or to people the
operator already knows, so a generated `@msgwing.com` sender costs nothing -
where a WooCommerce receipt from an unfamiliar domain would cost the sale.

Same contract as its three siblings: generated, `--check`ed in CI, orphans
removed, and every field name in the JSON read off the vendor's own
documentation rather than recalled.

    python tools/build-app-pages.py            # rewrite the pages
    python tools/build-app-pages.py --check    # fail if anything would change
"""

import argparse
import json
import pathlib
import sys

KORZEN = pathlib.Path(__file__).resolve().parent.parent
DANE = KORZEN / "data" / "apps.json"
KATALOG = KORZEN / "docs" / "apps"
INDEKS = KORZEN / "docs" / "SELF-HOSTED.md"

LIMIT_TYTULU = 48
MIN_TYTULU = 8

# Wspolne wartosci polaczenia zyja w docs/APPS.md i sa tam jedynym zrodlem.
# Powtorzone tutaj tylko dla stron, ktore maja wlasne nazwy pol - kazda z nich
# odsyla do tamtej tabeli.
HOST = "mx.msgwing.com"


def zbuduj(wpis, aktualizacja, t):
    pola = wpis["fields"]

    czesci = [
        "---",
        f'title: "{t}"',
        f'description: "{wpis["name"]} sends '
        f'{wpis["sends"][0]}. What stops when Microsoft 365 refuses a '
        f'username and password in December 2026, and the exact settings '
        f'that keep it sending."',
        "---",
        "",
        "<!-- BEGIN GENERATED PAGE -->",
        "<!-- Generated by tools/build-app-pages.py from data/apps.json.",
        "     Edit the JSON, not this file - CI rejects the two disagreeing. -->",
        "",
        f"# {wpis['name']} email and the Microsoft 365 Basic auth shutdown",
        "",
        f"{wpis['name']} is {wpis['what']}. It sends:",
        "",
    ]

    czesci += [f"- {s}" for s in wpis["sends"]]
    czesci += [
        "",
        "None of that is noisy, and none of it is noticed when it stops. Mail "
        "that is never sent leaves no error on any screen anybody looks at.",
        "",
        "## What changes at the end of December 2026",
        "",
        "If these messages go out through Microsoft 365 with a username and a "
        "password, Exchange Online stops accepting that by default. Not "
        "throttles — refuses. An administrator can switch it back on, which "
        "buys time rather than solving it: Microsoft announces the final "
        "removal date in the second half of 2027, and tenants created after "
        "December 2026 do not get the option at all.",
        "",
        "[Which of the four you are looking at](../ERROR-MESSAGES.md) "
        "is decided "
        "by the exact string the server sends back.",
        "",
        "## Why this application fits a free relay",
        "",
        wpis["why_it_fits"],
        "",
        "That is the honest test, and it is worth applying before the "
        "settings: mail leaves from a generated `@msgwing.com` address rather "
        "than your own domain, and the cap is 200 messages a day. For an "
        f"invoice or a shop receipt that is disqualifying. For {wpis['name']} "
        "it usually is not.",
        "",
        "## Settings",
        "",
        wpis["where"],
        "",
    ]

    if pola:
        czesci += [
            "| Setting | Value |",
            "| --- | --- |",
        ]
        czesci += [f"| `{k}` | `{v}` |" if not v.startswith("your ")
                   else f"| `{k}` | {v} |" for k, v in pola]
    else:
        czesci += [
            "| Setting | Value |",
            "| --- | --- |",
            f"| SMTP host | `{HOST}` |",
            "| Port | `587` (STARTTLS) or `465` (SSL/TLS) |",
            "| Encryption | STARTTLS on 587, or SSL/TLS on 465 — required |",
            "| Username | your `@msgwing.com` login |",
            "| Password | your `@msgwing.com` password |",
            "| From address | your `@msgwing.com` login |",
        ]

    czesci += [
        "",
        "Register at [msgwing.com](https://msgwing.com) first — the login and "
        "password are generated and shown once.",
        "",
        "## The part worth reading twice",
        "",
        wpis["caveat"],
        "",
        "## Where these names come from",
        "",
        f"Every field above was read off [{wpis['source_title']}]"
        f"({wpis['source']}), {wpis['name']}'s own documentation, rather than "
        "recalled. If that page and this one disagree, that page is right and "
        "this one is out of date — "
        "[say so](https://github.com/msgwing/ZeroSMTP/issues/new/choose).",
        "",
        "## Related",
        "",
        "- [Other self-hosted applications](../SELF-HOSTED.md)",
        "- [Connection values and every other application](../APPS.md)",
        "- [All SMTP AUTH error messages](../ERROR-MESSAGES.md)",
        "- [Tools that are a better fit than this one](../ALTERNATIVES.md)",
        "",
        f"*Last reviewed {aktualizacja}.*",
        "",
    ]

    return "\n".join(czesci)


def zbuduj_indeks(wpisy, aktualizacja):
    w = [
        "---",
        'title: "Self-hosted apps after the SMTP AUTH shutdown"',
        'description: "Immich, Vaultwarden, Gitea and Authelia send a handful '
        'of messages a month to people you already know. What stops when '
        'Microsoft 365 refuses a username and password, and the exact '
        'settings that keep each of them sending."',
        "---",
        "",
        "<!-- BEGIN GENERATED PAGE -->",
        "<!-- Generated by tools/build-app-pages.py from data/apps.json. -->",
        "",
        "# Self-hosted applications and the Basic auth shutdown",
        "",
        "The applications on this page have something in common that decides "
        "whether a free relay is the right answer for them: **they mail "
        "people who already know who you are.**",
        "",
        "An invitation to your own photo library, a password reset for your "
        "own Git server, a second-factor enrolment on your own login portal. "
        "Nobody is deciding whether to trust the sender, so a generated "
        "`@msgwing.com` address costs nothing. A shop receipt from an "
        "unfamiliar domain costs the sale — which is why "
        "[WooCommerce is handled differently](WORDPRESS.md).",
        "",
        "| Application | What its mail is for |",
        "|---|---|",
    ]

    for e in wpisy:
        w.append(f"| [{e['name']}](apps/{e['slug']}.md) | {e['sends'][0]} |")

    w += [
        "",
        "Each page names the exact settings, quotes where they came from, and "
        "states the one limit most likely to catch you out on that particular "
        "application.",
        "",
        "## What is not here",
        "",
        "Netdata, Jellyfin, Paperless-ngx, Portainer, changedetection.io and "
        "Wiki.js are all in the same position and are not covered yet. They "
        "are missing because nobody has read their documentation carefully "
        "enough to name the settings without guessing, not because they do "
        "not fit.",
        "",
        "[Tell us which one you run](https://github.com/msgwing/ZeroSMTP/"
        "issues/new/choose) and it moves up the list.",
        "",
        "## Related",
        "",
        "- [Connection values and every other application](APPS.md)",
        "- [WordPress and WooCommerce](WORDPRESS.md)",
        "- [What breaks at the end of December 2026](AFFECTED-SYSTEMS.md)",
        "- [Tools that are a better fit than this one](ALTERNATIVES.md)",
        "",
        f"*Last reviewed {aktualizacja}.*",
        "",
    ]

    return "\n".join(w)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if anything is out of date instead of rewriting it")
    args = ap.parse_args()

    dane = json.loads(DANE.read_text(encoding="utf-8"))
    wpisy = dane["entries"]

    slugi = [w["slug"] for w in wpisy]
    if len(set(slugi)) != len(slugi):
        print("Duplicate slugs - one page would silently overwrite another.")
        return 1

    # Kazde pole na tych stronach jest cytatem z cudzej dokumentacji. Wpis bez
    # zrodla to wpis, ktorego nikt nie sprawdzil - a strona z wymyslona nazwa
    # zmiennej kompromituje pozostale.
    bez = [w["slug"] for w in wpisy
           if not w.get("source", "").startswith("https://")]
    if bez:
        print("Entries without a source URL - every field name has to be "
              "traceable to the vendor's own page:")
        for s in bez:
            print(f"  {s}")
        return 1

    # `caveat` jest obowiazkowe. Wpis bez uczciwego ograniczenia jest reklama,
    # a reklama na stronie technicznej kosztuje zaufanie calej reszty.
    bez_zastrzezen = [w["slug"] for w in wpisy if not w.get("caveat", "").strip()]
    if bez_zastrzezen:
        print("Entries without a caveat - an entry with no honest limit is an "
              "advert:")
        for s in bez_zastrzezen:
            print(f"  {s}")
        return 1

    tytuly = {w["slug"]: f"{w['name']} email after Basic auth" for w in wpisy}

    zle = [s for s, t in tytuly.items()
           if not MIN_TYTULU <= len(t) <= LIMIT_TYTULU]
    if zle:
        print(f"Titles outside the {MIN_TYTULU}-{LIMIT_TYTULU} character "
              f"budget:")
        for s in zle:
            print(f"  {len(tytuly[s])}: {tytuly[s]}")
        return 1

    licznik = {}
    for s, t in tytuly.items():
        licznik.setdefault(t, []).append(s)
    zdublowane = {t: sl for t, sl in licznik.items() if len(sl) > 1}
    if zdublowane:
        print("Duplicate titles - a search engine will show only one of them:")
        for t, sl in zdublowane.items():
            print(f"  {t!r}: {', '.join(sl)}")
        return 1

    wyjscia = {
        KATALOG / f"{w['slug']}.md": zbuduj(w, dane["updated"], tytuly[w["slug"]])
        for w in wpisy
    }
    wyjscia[INDEKS] = zbuduj_indeks(wpisy, dane["updated"])

    # Bramka postawiona po tym, jak pierwszy przebieg wypuscil cztery
    # odnosniki do ERROR-MESSAGES.md z katalogu docs/apps/, gdzie tego pliku
    # nie ma. Sciezki wzgledne w generatorze pisza sie z perspektywy pliku
    # wyjsciowego, a ta perspektywa jest inna dla strony i dla indeksu.
    import re as _re
    martwe = []
    for p, t in wyjscia.items():
        for cel in _re.findall(r"\]\(([^)#:]+\.md)\)", t):
            if not (p.parent / cel).exists():
                martwe.append(
                    f"{p.relative_to(KORZEN).as_posix()} -> {cel}")
    if martwe:
        print("Links that resolve to nothing:")
        for m in martwe:
            print(f"  {m}")
        return 1

    istniejace = set(KATALOG.glob("*.md")) if KATALOG.exists() else set()
    osierocone = sorted(istniejace - set(wyjscia))

    def sciezka(p):
        return p.relative_to(KORZEN).as_posix()

    if args.check:
        rozne = [
            p for p, t in wyjscia.items()
            if not p.exists() or p.read_text(encoding="utf-8") != t
        ]
        if rozne or osierocone:
            for p in rozne:
                print(f"out of date: {sciezka(p)}")
            for p in osierocone:
                print(f"orphaned:    {sciezka(p)}")
            print("Run:  python tools/build-app-pages.py")
            return 1
        print(f"{len(wyjscia)} application pages match data/apps.json")
        return 0

    KATALOG.mkdir(parents=True, exist_ok=True)
    zapisane = 0
    for p, t in wyjscia.items():
        if not p.exists() or p.read_text(encoding="utf-8") != t:
            p.write_bytes(t.encode())
            zapisane += 1
    for p in osierocone:
        p.unlink()
        print(f"removed orphaned page: {sciezka(p)}")

    print(f"{zapisane} file(s) rewritten, {len(osierocone)} removed "
          f"({len(wpisy)} applications)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
